### ISSUE TITLE
Regular loss of Tracking 

### ISSUE THREAD

**Issue by Melvincraft** [artumino/VRScreenCap#32]
Using a quest 3 and xbox controller with virtual desktop and steamvr. 

While running any game in vrscreencap, after about 5 minutes of playing it loses tracking and becomes head-locked. Waking up the controllers fixes it. Used to happen with quest 2 also, so it's not a new issue.

Have tried latest 2.0 beta of steamvr but the issue is still present.

This doesn't happen with any other VR game or app.

**Comment by artumino** [comment]
Are you by any chance using the hand tracking feature of Virtual Desktop?
It tends to leave controllers near the head when it's not tracking them correctly, this causes the recentering logic to kick in.

There's an option to disable this behavior in Virtual Desktop. As an alternative I'll also add a launch parameter to ignore all inputs when launching the app. Launching the app with the --no-input flag should ignore them and avoid the recentering.
