### ISSUE TITLE
Black screen on all headsets

### ISSUE THREAD

**Issue by RAGEdemon** [artumino/VRScreenCap#9]
Thank you for this.

Issue: Native Vulkan OpenXR (SteamVR/Oculus) as well as WMR via OpenXR-Vk-D3D12 give black screen.

More details:
WMR HP Reverb G2 + [OpenXR-Vk-D3D12](https://github.com/mbucchia/OpenXR-Vk-D3D12) gave black screen. I opened issue with the developer of OpenXR-Vk-D3D12. He tested it with a Quest 2 and a native SteamVR head set, both of which support native OpenXR Vulkan. He too got black screen.

His conclusion was that the issue seems to be with VRScreenCap?

[OpenXR-Vk-D3D12 Issue Thread here](https://github.com/mbucchia/OpenXR-Vk-D3D12/issues/1 )

Full reply from developer:
--------------------------
_Hello,

I have downloaded v0.1.0 of this application from here: https://github.com/artumino/VRScreenCap/releases/tag/0.1.0

I have tested it with:

    Oculus Quest 2
    SteamVR OpenXR runtime

Both of these OpenXR runtimes natively support Vulkan (ie: can be trusted). I get black screen for both.

As far as I can tell, the issue is not with OpenXR-Vk-D3D12, since the app is giving me a black screen with 2 fully qualified OpenXR runtimes.

Please contact the developer of that application._

**Comment by artumino** [comment]
Hi, right now if no geo-11 game is running when VRScreenCap is launched nothing will be shown on the screen.
Have you tried closing VRScreenCap, launching the game, and then relaunching VRScreenCap?

There should be an `output.log` file near the executable with some information on what's happening.

**Comment by RAGEdemon** [comment]
[output.log](https://github.com/artumino/VRScreenCap/files/9227164/output.log)

Please find attached. Game is running and works fine with katanga.

**Comment by RAGEdemon** [comment]
Update: It works!

I clean installed the game, the fix, geo-11; then made manual changes to the .ini files to the point where a TaB image shows in screen as when Katanga works. I can't pinpoint the exact cause of earlier failure.

Only problem now is that the screen is very washed out - blacks are very light gray? 
If I exit VRScreenCap and open Katanga instead, colours re perfect.

Suggestions appreciated, thank you.

**Comment by artumino** [comment]
It's probably a difference in colorspace that I'm not accounting for, can you attach the log of a working instance again?
Also what game is it?

**Comment by RAGEdemon** [comment]
[output.log](https://github.com/artumino/VRScreenCap/files/9229416/output.log)

Game = Visage.

Thank you for your work.

**Comment by artumino** [comment]
I can confirm I was doing the color space calculations wrong, should be fixed in the next release

**Comment by artumino** [comment]
Just published version 0.2.0, it should fix the issue

**Comment by RAGEdemon** [comment]
Thank you - one of our cummunity members reports it as working... and wishes for a way to centre the screen... but that is another issue completely.

We're greatly looking forward to seeing more development of this app if you have the time - thank you :)

**Comment by artumino** [comment]
Thanks for the report!
In theory, the recentering logic should be handled by the OpenXR runtime, although I've noticed that in SteamVR the "Recenter Seated Position" has been moved to a menu only accessible from the desktop. I'll surely consider adding an in-app recentering mechanism.
